-- MySQL Script generated by MySQL Workbench
-- Fri Sep  8 11:05:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_camagru
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_camagru
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_camagru` DEFAULT CHARACTER SET utf8 ;
USE `db_camagru` ;

-- -----------------------------------------------------
-- Table `db_camagru`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_camagru`.`users` (
  `id` INT(11) NOT NULL,
  `nom` VARCHAR(50) NULL DEFAULT NULL,
  `prenom` VARCHAR(50) NULL DEFAULT NULL,
  `login` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `mail` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_camagru`.`pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_camagru`.`pictures` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `file_url` VARCHAR(255) NULL,
  `user_id` INT NULL,
  `crea_date` DATETIME NULL,
  `nbr_posts` INT NULL,
  `nbr_like` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pictures_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_pictures_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_camagru`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_camagru`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_camagru`.`comments` (
  `id` INT NULL,
  `title` VARCHAR(100) NULL,
  `content` TEXT NULL,
  `date` DATETIME NULL,
  `type` VARCHAR(100) NULL,
  `user_id` INT NULL COMMENT 'Détermine le user qui a ecrit le commentaire',
  `picture_id` INT NULL COMMENT 'determine la liaison a une photo',
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users_idx` (`user_id` ASC),
  INDEX `fk_comments_pictures1_idx` (`picture_id` ASC),
  CONSTRAINT `fk_comments_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_camagru`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_pictures1`
    FOREIGN KEY (`picture_id`)
    REFERENCES `db_camagru`.`pictures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_camagru`.`calcs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_camagru`.`calcs` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `file_url` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
